[4주차/필수] 서버 통신_xml
NOW-SOPT-ANDROID/gaeul-lee pull request #11
Opened 2024-04-30 09:55 UTC by gaeulzzang

## Related issue 🛠
- #10 

## Work Description ✏️
#### 서버 통신을 통해 회원가입/로그인/내 정보 구현하기
- [x] 회원가입 서버 통신
- [x] 로그인 서버 통신
- [x] 로그인 성공했을 경우 유저아이디 토스트 메세지에 넣기
- [x] 비밀번호 변경 기능
- [x] 홈 프래그먼트에 Open API 연결하기
- [x] 홈 프래그먼트 그리드 레이아웃으로 변경
- [x] 툴바 사용

## Screenshot 📸

https://github.com/NOW-SOPT-ANDROID/gaeul-lee/assets/91470334/382d4116-5502-47af-a048-189c92f7e53c

## Uncompleted Tasks 😅
- [ ] 로그아웃할 때 다이얼로그 띄우기

## To Reviewers 📢
인터셉터를 안사용했습니다... 그리고 오픈 API 불러오는 로직을 뷰모델에서 구현하면 어댑터에 빈 리스트만 들어가서 로직을 한 곳에 와다다 작성했어여😔😔

2024-05-01 09:38 UTC, s9hn requested changes
안녕하세요. 가을님 리뷰어로 함께하게 된 명예OB 김세훈입니다. 앞으로 잘 부탁드립니다.

과제 구현하시느라 고생하셨습니다!
코드를 읽다가 상세한 리뷰보단 공통적으로 적용할 수 있는 리뷰가 도움이 될 것 같아서 아래사항부터 차근차근 리팩터링하면 좋을 것 같습니다 :)


### 우리는 코드를 어떤식으로 작성해야 할까요? 
코드는 누가 읽는건가요? 
과연 내가 작성한 코드는 나만 볼까요? 
그렇다면 1주일 뒤의 내가 혹은 1년 뒤의 내가 이 코드를 봐도 온전히 이해할 수 있을까요?

'이름'이란건 그 자체로 굉장히 강력하고 유의미한 효과가 있습니다.
앉을 수 있는 사물에게 '의자'란 이름을 부여하면, 그것의 형태가 어떻게 변하든 100년이 지나도 그 사물은 우리가 '의자'라는 이름으로 부를 수 있습니다. 이는 코드에도 동일하게 적용됩니다.
좋은 코드란건 굉장히 열린 질문이고 어렵지만 이를 가장 간단하게 구현할 수 있는 첫번째 방법은 네이밍입니다.
또한 네이밍에 대해 개발자들간의 규약들을 정의해놓은 문서들도 많습니다.
'이 변수는 무엇을 담고 있는지', '이 함수는 무엇을 하는지' 를 보다 명확하게 나타내주세요. 
(개인적으로 공통규약의 축약어가 아닌 이상 줄여쓰는 것은 지양합니다. 이름이 길어지는 걸 두려워하지마세요.)

- [코틀린 컨벤션](https://kotlinlang.org/docs/coding-conventions.html#source-file-names)
- [PRND 컨벤션](https://github.com/PRNDcompany/android-style-guide/blob/main/Kotlin.md)
- [객체지향 생활체조 원칙](https://s2ehun.tistory.com/5)

### 함수란?
일반적으로 수학에서의 함수는 두 변수에 대하여 '하나의 값이 정해지면 그에 따른 결과 값이 오직 하나로 결정'됩니다. 우리가 작성해야할 함수도 그렇습니다.
함수는 어디서 호출하든 그 '이름에 해당하는 행위만을 수행함'을 보장할 수 있어야합니다.
함수는 객체가 수행할 가장 작은 단위의 행위(=동작)입니다. 
함수가 이름에 걸맞게 가능한 한 가지 일만을 수행할 수 있도록 리팩터링해보세요.
(함수의 네이밍 혹은 함수 자체가 너무 많은 일을 포함하고 있진 않은지 의심해보세요)

- [Kotlin Function 만들기](https://developer.android.com/codelabs/basic-android-kotlin-compose-functions?hl=ko#7)

2024-05-01 09:38 UTC, s9hn commented on app/src/main/java/com/sopt/now/ApiFactory.kt
> +    fun retrofit(url: String): Retrofit {
ApiFactory는 전역에 공개되는 API입니다.
다른 개발자에게 'retrofit'이라는 함수를 공개할 필요가 있나요?

2024-05-01 09:38 UTC, s9hn commented on app/src/main/java/com/sopt/now/ApiFactory.kt
> +    val friendService = ApiFactory.create<FriendService>(FRIEND_BASE_URL)
이런 형태로 별도의 ServicePool을 관리한다면, 실제 프로덕션 코드일 경우 굉장히 많은 서비스 객체가 있을 것 같습니다.
내가 사용하지 않는 서비스 객체도 미리 만들어둘 필요가 있을까요?

2024-05-01 09:38 UTC, s9hn commented on app/src/main/java/com/sopt/now/activity/ChangePwdActivity.kt
> +    private fun changePwdBtnClick() {
해당 함수 이름만 본다면, '패스워드 버튼 클릭(이벤트 등)을 변경한다'로 유추해볼 수 있을 것 같습니다.

2024-05-01 09:38 UTC, s9hn commented on app/src/main/java/com/sopt/now/activity/ChangePwdActivity.kt
> +                        Log.e("ChangePwd", "data: $data")
우리가 merge를 하는 목적, PR을 체크하는 목적은 무엇인가요?
다른 개발자가 보았을 때 Log는 유의미한 코드일까요? 
내가 작성하는 코드가 실제 프로덕션의 기능상 유의미한지 검토할 필요가 있습니다

2024-05-01 09:38 UTC, s9hn commented on app/src/main/java/com/sopt/now/activity/ChangePwdActivity.kt
> +        val checkPwd = binding.etCheckPwd.text.toString()
프로퍼티 이름은 명사형태로 작성해주세요

2024-05-01 09:38 UTC, s9hn commented on app/src/main/java/com/sopt/now/activity/LoginActivity.kt
> +    private fun initViews() {
이 함수는 정말 뷰를 초기화하고 있나요?

2024-05-01 09:38 UTC, s9hn commented on app/src/main/java/com/sopt/now/fragment/HomeFragment.kt
>      private val viewModel = HomeViewModel()
뷰모델 인스턴스는 어떻게 생성하는 것이 좋을까요?
안드로이드는 공식문서가 굉장히 잘 마련되어 있습니다! 
https://developer.android.com/topic/libraries/architecture/viewmodel?hl=ko

2024-05-04 22:48 UTC, jihyunniiii reviewed
고생하셨서요

2024-05-04 22:48 UTC, jihyunniiii commented on app/src/main/java/com/sopt/now/activity/LoginActivity.kt
> +                    .show()
다이얼로그 사용 좋네요

2024-05-04 22:48 UTC, jihyunniiii commented on app/src/main/java/com/sopt/now/fragment/HomeFragment.kt
> +                    Toast.makeText(requireContext(), "친구 목록을 불러오는 데 실패했습니다", Toast.LENGTH_SHORT)
여기도 스트링 추출을 해보시면 좋을 것 같습니다 ~

2024-05-04 22:48 UTC, jihyunniiii commented on app/src/main/java/com/sopt/now/fragment/HomeFragment.kt
> +                        mockFriendList.add(Friend(friend.avatar, friend.firstName, friend.email))
이제 mock 데이터가 아니니까 네이밍을 변경해주면 좋겠네요

2024-05-04 22:48 UTC, jihyunniiii commented on app/src/main/java/com/sopt/now/friend/FriendViewHolder.kt
> +            Glide.with(ivProfile.context)
오 glide를 쓰셨군요 ! 저는 coil을 주로 쓰는데 얘도 공부 해보시면 좋을 것 같습니다 ~

2024-05-04 22:48 UTC, jihyunniiii commented on app/src/main/java/com/sopt/now/viewmodel/HomeViewModel.kt
> +    }
init 블록에 서버 통신 등의 무거운 작업을 넣는 것은 피하는 것이 좋은데요! 왜 그런지에 대한 이유를 찾아보면 좋을 것 같아요

2024-05-04 22:48 UTC, jihyunniiii commented on app/src/main/res/layout/activity_change_pwd.xml
> +        app:layout_constraintTop_toBottomOf="@+id/tv_check_pwd" />
```suggestion
        app:layout_constraintTop_toBottomOf="@id/tv_check_pwd" />
```
습관화 합시다

2024-05-05 06:38 UTC, yskim6772 approved these changes
수고 많으셨습니당-!

2024-05-05 06:38 UTC, yskim6772 commented on app/src/main/java/com/sopt/now/fragment/HomeFragment.kt
>          get() = requireNotNull(_binding)
이 부분을 BindingFragment로 분리해서 상속 받아서 사용해도 좋을 것 같아요 !

2024-05-05 06:38 UTC, yskim6772 commented on app/src/main/java/com/sopt/now/fragment/HomeFragment.kt
> +            layoutManager = GridLayoutManager(requireContext(), 2)
Grid 레이아웃으로 표현하셨군요 ! 깔끔하고 좋네용

2024-05-05 06:38 UTC, yskim6772 commented on app/src/main/java/com/sopt/now/fragment/MyPageFragment.kt
> +
로그아웃 부분에 다이얼로그 띄우기까지 ! 굿굿

2024-05-05 06:38 UTC, yskim6772 commented on app/src/main/java/com/sopt/now/request/RequestChangePwdDto.kt
> +)
저도 리팩 때 비밀번호 변경 기능까지 후딱 추가해야겠어용 ~

2024-05-05 06:38 UTC, yskim6772 commented on app/src/main/java/com/sopt/now/viewmodel/HomeViewModel.kt
> +            }
로그들을 지워줘도 좋을 것 같아요 !

2024-05-05 10:57 UTC, leeseokchan00 commented
이번에 합동세미나 들어가기 전에 Mvvm 공부를 해보면 좋을 것 같아요. 물론 지금의 방법도 잘 동작하지만 다른 사람들과 같이 작업하는 경우에는 충돌도 많이나고 조금 힘들 수도 있을 것 입니다. 
액티비티에는 ui에 관련된 로직만 넣어주고, 데이터의 처리는 뷰모델에서 할 수 있게 만들어보면 좋을 것 같아요~ 그리고 폴더링도 OB분들 코드나 안드로이드 공식 깃허브 참고해서 공부해보면 좋습니다~

2024-05-05 11:13 UTC, leeseokchan00 approved these changes
고생하셨습니다~~~

2024-05-05 11:13 UTC, leeseokchan00 commented on app/src/main/java/com/sopt/now/activity/LoginActivity.kt
> +                    ).show()
지금 Activity가 너무 방대하잖아요. 그래서 login()함수 처럼 데이터를 처리하는 함수는 뷰모델로 옮겨주면 좋습니다. 데이터 레이어를 두어서 뷰모델이 데이터레이어를, 데이터 레이어에서 외부로 통신할 수 있는 구조가 이상적이라고 합니다.🐸

2024-05-05 11:13 UTC, leeseokchan00 commented on app/src/main/java/com/sopt/now/fragment/MyPageFragment.kt
> +            activity?.startActivity(intent)
여기도 스코프 함수를 사용하면 더 코틀린에 맞는 코드로 바꿀 수 있을 것 같아여

2024-05-05 11:13 UTC, leeseokchan00 commented on app/src/main/java/com/sopt/now/request/RequestSignUpDto.kt
> +    val phone: String,
이미 아실지 모르겠지만, 안드로이드 스튜디오에 json to kotlin 이라는 플러그인을 설치하면, 알아서 json을 kotlin data class로 만들어주는 플러그인이 있답니다🙀

2024-05-05 11:13 UTC, leeseokchan00 commented on app/src/main/java/com/sopt/now/fragment/HomeFragment.kt
> +    private lateinit var friendAdapter: FriendAdapter
요렇게 뷰모델을 사용하게되면 생명주기에 문제가 생긴답니다!

2024-05-05 15:18 UTC, junseo511 reviewed
과제구현 고생 많으셨습니다~~!!

이미 많은 분들이 휩쓸고 가셨네용 ㄷㄷ ㅋㅋㅋㅋ 우리 합세조 파이팅!!!!

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/ChangePwdActivity.kt
> +            newPasswordVerification = checkPwd,
변수명에 일관성을 지켜주시면 좋을듯합니다~~!!

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/LoginActivity.kt
> +    private fun initViews() {
initViews라는 이름이 조금 애매하게 느껴지네요!! 🤔

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/LoginActivity.kt
> +                    ).show()
비즈니스 로직이 뭘까요?

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/LoginActivity.kt
> +        )
변수를 따로 초기화해주지 않고 사용하면 코드가 짧아질 수 있을 것 같아용

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/fragment/HomeFragment.kt
> +        ServicePool.friendService.getFriends(2).enqueue(object : Callback<ResponseFriendsDto> {
2가 어떤 숫자인가요? 따로 const val 등으로 숫자에 의미를 부여해주면 좋을 것 같아요!

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/fragment/MyPageFragment.kt
> +            AlertDialog.Builder(requireContext()).run {
loginActivity랑 구현방식이 조금 다른데 run으로 묶고 람다로 묶어서 구별하신 차이가 있으신가요?

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/fragment/MyPageFragment.kt
> +                    intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
백스택 날리는거 좋슴당

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/friend/FriendViewHolder.kt
> +            Glide.with(ivProfile.context)
Coil과 Glide는 여러 차이점이 있는데 공부해보시고, 상황에 맞게 선택해서 쓰는게 좋을 것 같아요~~!!

2024-05-05 15:18 UTC, junseo511 commented on app/src/main/java/com/sopt/now/friend/Friend.kt
API를 연결했는데 이친구를 남겨서 어떻게 쓰고 계신가용

2024-05-06 00:28 UTC, leeseokchan00 commented
> 과제구현 고생 많으셨습니다~~!!
> 
> 이미 많은 분들이 휩쓸고 가셨네용 ㄷㄷ ㅋㅋㅋㅋ 우리 합세조 파이팅!!!!

2024-05-06 00:28 UTC, leeseokchan00 commented
> > 과제구현 고생 많으셨습니다~~!!
> > 이미 많은 분들이 휩쓸고 가셨네용 ㄷㄷ ㅋㅋㅋㅋ 우리 합세조 파이팅!!!!

2024-05-06 05:28 UTC, gaeulzzang commented on app/src/main/java/com/sopt/now/activity/ChangePwdActivity.kt
> +            newPasswordVerification = checkPwd,
어머... 이상한 변수를 썼네용😲 알려주셔서 감사합니다~

2024-05-06 08:50 UTC, merged